-- 1.
SELECT STUDENT_NAME 학생이름, STUDENT_ADDRESS 학생주소
FROM TB_STUDENT ts 
ORDER BY 1;

-- 2.
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT ts 
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

-- 3.
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS 거주지
FROM TB_STUDENT ts 
WHERE SUBSTR(STUDENT_ADDRESS, 1, 3) IN ('강원도','경기도')
AND NOT STUDENT_NO LIKE 'A%' 
ORDER BY 1;

-- 4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR tp
WHERE DEPARTMENT_NO = (
	SELECT DEPARTMENT_NO 
	FROM TB_DEPARTMENT td 
	WHERE DEPARTMENT_NAME = '법학과')
ORDER BY 2;

-- 5.
SELECT STUDENT_NO, TO_CHAR(POINT, 9.99)
FROM TB_GRADE tg 
WHERE CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY 2 DESC, STUDENT_NO;

-- 6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO)
ORDER BY SUBSTR(STUDENT_NAME,2);

-- 7.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS tc 
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO);

-- 8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS tc
JOIN TB_CLASS_PROFESSOR tcp USING (CLASS_NO)
JOIN TB_PROFESSOR tp USING(PROFESSOR_NO);

-- 9.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS tc
JOIN TB_CLASS_PROFESSOR tcp USING (CLASS_NO)
JOIN TB_PROFESSOR tp USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT td ON(td.DEPARTMENT_NO = tp.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

-- 10.
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT),1) 
FROM TB_GRADE tg 
JOIN TB_STUDENT ts USING (STUDENT_NO)
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO;

-- 11.
SELECT DEPARTMENT_NAME "학과이름", "학생이름", "지도교수이름"
FROM (
	SELECT STUDENT_NAME "학생이름", PROFESSOR_NAME "지도교수이름" , ts.DEPARTMENT_NO
	FROM TB_STUDENT ts 
	JOIN TB_PROFESSOR tp ON (ts.COACH_PROFESSOR_NO = tp.PROFESSOR_NO)
	WHERE STUDENT_NO = 'A313047'
) e
JOIN TB_DEPARTMENT td ON (td.DEPARTMENT_NO = e.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '경제학과'
GROUP BY DEPARTMENT_NAME, "학생이름", "지도교수이름";


SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT ts2 
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR tp ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';


-- 12.
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT ts 
JOIN TB_GRADE tg USING (STUDENT_NO)
WHERE CLASS_NO = (
	SELECT CLASS_NO
	FROM TB_CLASS tc 
	JOIN TB_GRADE USING (CLASS_NO)
	WHERE CLASS_NAME = '인간관계론'
	GROUP BY CLASS_NO
) AND SUBSTR(TERM_NO,1,4) = '2007'
GROUP BY STUDENT_NAME, TERM_NO;

SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT ts 
JOIN TB_GRADE tg USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE CLASS_NAME = '인간관계론' 
AND TERM_NO LIKE '2007%';

-- 13.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS tc 
LEFT JOIN TB_CLASS_PROFESSOR tcp USING (CLASS_NO)
LEFT JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO)
WHERE PROFESSOR_NO IS NULL
AND CATEGORY = '예체능'
ORDER BY DEPARTMENT_NO , CLASS_TYPE DESC, CLASS_NAME;


-- 14.
SELECT e.STUDENT_NAME "학생이름",
	CASE WHEN e.COACH_PROFESSOR_NO IS NULL THEN '지도교수 미지정'
		 ELSE tp.PROFESSOR_NAME 
	END "지도교수"
FROM (
	SELECT STUDENT_NO, STUDENT_NAME, COACH_PROFESSOR_NO
	FROM TB_STUDENT ts 
	JOIN TB_DEPARTMENT td ON(ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
	WHERE DEPARTMENT_NAME = '서반아어학과'
) e
LEFT JOIN TB_PROFESSOR tp ON (e.COACH_PROFESSOR_NO = tp.PROFESSOR_NO)
ORDER BY e.STUDENT_NO;


SELECT STUDENT_NAME, NVL(PROFESSOR_NAME, '지도교수 미지정')
FROM TB_STUDENT ts 
LEFT JOIN TB_PROFESSOR tp ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT td ON (ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;

-- 15.
SELECT STUDENT_NO "학번", STUDENT_NAME "학생이름", DEPARTMENT_NAME "학과이름", ROUND(AVG(POINT),1) "평점"
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO)
JOIN TB_GRADE tg USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO , STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4
ORDER BY 1;

-- 16.
SELECT CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_CLASS tc 
JOIN TB_GRADE tg USING(CLASS_NO)
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '%전공%'
GROUP BY CLASS_NO , CLASS_NAME;

-- 17.
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT ts 
WHERE DEPARTMENT_NO  = (
	SELECT DEPARTMENT_NO 
	FROM TB_STUDENT ts 
	WHERE STUDENT_NAME = '최경희'
);

-- 18.
SELECT ts.STUDENT_NO, ts.STUDENT_NAME
FROM TB_STUDENT ts 
JOIN TB_GRADE tg ON (ts.STUDENT_NO = tg.STUDENT_NO)
JOIN TB_DEPARTMENT td ON (ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
WHERE td.DEPARTMENT_NAME = '국어국문학과'
GROUP BY ts.STUDENT_NO, ts.STUDENT_NAME
HAVING AVG(POINT) = (
	SELECT MAX(AVG(POINT))
	FROM TB_GRADE tg2
	JOIN TB_STUDENT ts2 USING(STUDENT_NO)
	WHERE DEPARTMENT_NO = '001'
	GROUP BY STUDENT_NO
);

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT ts
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
JOIN TB_GRADE tg USING(STUDENT_NO)
WHERE td.DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (
	SELECT MAX(AVG(POINT))
	FROM TB_STUDENT ts
	JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
	JOIN TB_GRADE tg USING(STUDENT_NO)
	WHERE td.DEPARTMENT_NAME = '국어국문학과'
	GROUP BY STUDENT_NO, STUDENT_NAME
);

-- INLINE VIEW 활용
SELECT STUDENT_NO, STUDENT_NAME
FROM (
	SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT)
	FROM TB_GRADE tg 
	JOIN TB_STUDENT ts USING (STUDENT_NO)
	JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO)
	WHERE DEPARTMENT_NAME = '국어국문학과'
	GROUP BY STUDENT_NO, STUDENT_NAME
	ORDER BY 3 DESC
)
WHERE ROWNUM = 1;

-- 19.
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1) "전공평점"
FROM TB_DEPARTMENT td
JOIN TB_CLASS tc USING (DEPARTMENT_NO)
JOIN TB_GRADE tg USING (CLASS_NO)
WHERE CATEGORY = (
	SELECT CATEGORY 
	FROM TB_DEPARTMENT
	WHERE DEPARTMENT_NAME = '환경조경학과'
)
AND CLASS_TYPE LIKE '전공%'
GROUP BY DEPARTMENT_NAME 
ORDER BY 1;






