-- 1.
CREATE TABLE TB_CATEGORY (
	NAME VARCHAR2(10),
	USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2.
CREATE TABLE TB_CLASS_TYPE (
	NO VARCHAR2(5) CONSTRAINT TCTYPE_PK PRIMARY KEY,
	NAME VARCHAR2(10)
);

-- 3.
ALTER TABLE TB_CATEGORY
ADD CONSTRAINT TCATE_PK PRIMARY KEY(NAME);

-- 4. 
ALTER TABLE TB_CLASS_TYPE 
MODIFY NAME NOT NULL;

-- 5.
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10) 
MODIFY NAME VARCHAR(20);

-- 6.
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;

-- 7.
ALTER TABLE TB_CATEGORY 
RENAME CONSTRAINT PK_CATEGORY TO PK_CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT TCTYPE_PK TO PK_CLASS_TYPE_NO;

-- 8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

-- 9.
ALTER TABLE TB_DEPARTMENT 
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);

-- 10.
CREATE OR REPLACE VIEW VW_학생일반정보(학번, 학생이름, 주소)
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
	FROM TB_STUDENT ts ;

-- 11.
CREATE OR REPLACE VIEW VW_지도면담(학생이름, 학과이름, 지도교수이름)
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, NVL2(COACH_PROFESSOR_NO,PROFESSOR_NAME, '지도교수 미지정')
	FROM TB_STUDENT ts 
	LEFT JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO)
	LEFT JOIN TB_PROFESSOR tp ON COACH_PROFESSOR_NO = PROFESSOR_NO
	ORDER BY 2;

SELECT * FROM VW_지도면담;

-- 12.
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(*) STUDENT_COUNT
	FROM TB_DEPARTMENT td 
	JOIN TB_STUDENT ts USING (DEPARTMENT_NO)
	GROUP BY DEPARTMENT_NAME;

SELECT * FROM VW_학과별학생수;

-- 13.
UPDATE VW_학생일반정보
SET STUDENT_NAME = '오창정'
WHERE STUDENT_NO = 'A213046';

SELECT * FROM VW_학생일반정보 WHERE STUDENT_NO = 'A213046';
	
-- 14.
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
	FROM TB_STUDENT ts 
	WHERE STUDENT_NO = 'A213046' WITH READ ONLY;

-- 15.
SELECT 과목번호, 과목이름, "누적수강생수(명)"
FROM (
	SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름, COUNT(*) "누적수강생수(명)"
	FROM TB_GRADE tg 
	JOIN TB_CLASS tc USING (CLASS_NO)
	WHERE SUBSTR(TERM_NO,1,4) >= (SELECT MAX(SUBSTR(TERM_NO,1,4)) - 4 FROM TB_GRADE tg )
	GROUP BY CLASS_NO, CLASS_NAME 
	ORDER BY 3 DESC
) e
WHERE ROWNUM <= 3;













