


















SELECT *
FROM CHAT_ROOM
JOIN CHAT_MESSAGE cm USING(CHAT_ROOM_NO); 

SELECT
	A.CHAT_ROOM_NO,
	CHAT_TITLE,
	USER_NAME,
	C.ENROLL_DATE,
	(
		SELECT 
			COUNT(*)
		FROM CHAT_ROOM_JOIN B
		WHERE B.CHAT_ROOM_NO = A.CHAT_ROOM_NO
	) CNT
FROM CHAT_ROOM A
JOIN MEMBER M ON(USER_NO = CHAT_USER_NO)
JOIN CHAT_MESSAGE C ON(A.CHAT_ROOM_NO = C.CHAT_ROOM_NO)
WHERE A.CHAT_USER_NO = 1 AND A.STATUS = 'Y'
ORDER BY A.CHAT_ROOM_NO DESC;


SELECT
    A.CHAT_ROOM_NO,
    A.CHAT_TITLE,
    M.USER_NAME,
    C.ENROLL_DATE,
    COUNT(B.CHAT_ROOM_NO) AS CNT
FROM CHAT_ROOM A
JOIN MEMBER M ON A.CHAT_USER_NO = M.USER_NO
JOIN CHAT_MESSAGE C ON A.CHAT_ROOM_NO = C.CHAT_ROOM_NO
LEFT JOIN CHAT_ROOM_JOIN B ON A.CHAT_ROOM_NO = B.CHAT_ROOM_NO
WHERE A.CHAT_USER_NO = 1 AND A.STATUS = 'Y'
GROUP BY A.CHAT_ROOM_NO, A.CHAT_TITLE, M.USER_NAME, C.ENROLL_DATE
ORDER BY A.CHAT_ROOM_NO DESC;

SELECT *
FROM CHAT_ROOM
WHERE CHAT_USER_NO = 5 AND STATUS = 'Y';


SELECT *
FROM CHAT_ROOM cr 
JOIN CHAT_ROOM_JOIN crj USING(CHAT_ROOM_NO)
JOIN MEMBER m ON(crj.CHAT_USER_NO = m.USER_NO)
WHERE CHAT_ROOM_NO = 6 AND cr.STATUS = 'Y';


SELECT *
FROM CHAT_MESSAGE 
JOIN CHAT_ROOM USING(CHAT_ROOM_NO)
WHERE CHAT_ROOM_NO = 6 AND STATUS = 'Y';

SELECT * 
FROM "MEMBER" M
INNER JOIN FRIEND F ON F.FRIEND_USER2 = M.USER_NO AND F.FRIEND_USER1 = 2
JOIN IMAGE I ON M.USER_NO = I.FILE_WRITER AND I.FILE_LEVEL = 1;

SELECT *
FROM CHAT_MESSAGE 
JOIN CHAT_ROOM_JOIN USING(CHAT_ROOM_NO)
WHERE CHAT_ROOM_NO = 6;

SELECT A.CHAT_ROOM_NO, CHAT_TITLE, A.CHAT_USER_NO, USER_NICK ,
	(
		SELECT COUNT(*)
		FROM CHAT_ROOM_JOIN B
		WHERE B.CHAT_ROOM_NO = A.CHAT_ROOM_NO 
	) CNT
FROM CHAT_ROOM_JOIN A
JOIN MEMBER m ON(A.CHAT_USER_NO = USER_NO)
JOIN CHAT_ROOM C ON(A.CHAT_ROOM_NO = C.CHAT_ROOM_NO)
WHERE C.STATUS = 'Y' AND USER_NO = 
ORDER BY A.CHAT_ROOM_NO DESC;


SELECT CHAT_NO, CHAT_ROOM_NO, CHAT_USER_NO, CHAT_MESSAGE , cm.ENROLL_DATE, USER_NICK  
FROM CHAT_MESSAGE CM
JOIN MEMBER M ON(USER_NO = CHAT_USER_NO)
WHERE CHAT_ROOM_NO = 7;


SELECT CHAT_ROOM_NO, CHAT_TITLE, FILE_PATH, CHANGE_NAME, USER_NO, USER_NICK
FROM CHAT_ROOM_JOIN crj 
JOIN MEMBER ON(USER_NO = CHAT_USER_NO)
JOIN IMAGE i ON(FILE_WRITER = CHAT_USER_NO)
LEFT JOIN CHAT_ROOM USING(CHAT_ROOM_NO)
WHERE CHAT_ROOM_NO = 2 AND FILE_LEVEL = 1;

SELECT *
FROM CHAT_MESSAGE cm 
WHERE CHAT_USER_NO = 5
ORDER BY ENROLL_DATE DESC;





/*
 * 방번호, 방제목, 방사진(채팅방 내부 사용자에 따라 다름), 최신 메세지, 메세지 시간(1개)
 */

SELECT crj.CHAT_ROOM_NO , CHAT_TITLE, USER_NO, USER_NICK, FILE_PATH, CHANGE_NAME, cm.CHAT_MESSAGE, cm.ENROLL_DATE
FROM CHAT_ROOM cr 
LEFT JOIN CHAT_ROOM_JOIN crj ON(cr.CHAT_ROOM_NO = crj.CHAT_ROOM_NO)
LEFT JOIN CHAT_MESSAGE cm ON(cr.CHAT_ROOM_NO = cm.CHAT_ROOM_NO)
JOIN MEMBER m ON(crj.CHAT_USER_NO = m.USER_NO)
JOIN IMAGE ON(FILE_WRITER = crj.CHAT_USER_NO)
WHERE cr.CHAT_ROOM_NO = 1 AND cr.STATUS = 'Y' AND FILE_LEVEL = 1;

SELECT
    cm.CHAT_NO,
    cm.CHAT_ROOM_NO,
    cm.CHAT_USER_NO,
    cm.CHAT_MESSAGE,
    cm.ENROLL_DATE
FROM
    CHAT_MESSAGE cm
WHERE
    cm.CHAT_ROOM_NO = 1
    AND cm.ENROLL_DATE = (
        SELECT MAX(cm2.ENROLL_DATE)
        FROM CHAT_MESSAGE cm2
        WHERE cm2.CHAT_ROOM_NO = cm.CHAT_ROOM_NO
    );

SELECT DISTINCT FILE_PATH, CHANGE_NAME
FROM CHAT_ROOM_JOIN cm 
JOIN IMAGE ON (FILE_WRITER = CHAT_USER_NO)
WHERE CHAT_USER_NO = 5 AND FILE_LEVEL = 1 AND CHAT_ROOM_NO = 24;



SELECT 
    crj.CHAT_ROOM_NO,
    cr.CHAT_TITLE,
    crj.CHAT_USER_NO,
    m.USER_NICK,
    IMAGE.FILE_PATH,
    IMAGE.CHANGE_NAME,
    cm.CHAT_MESSAGE,
    cm.ENROLL_DATE
FROM 
    CHAT_ROOM cr
LEFT JOIN 
    CHAT_ROOM_JOIN crj ON (cr.CHAT_ROOM_NO = crj.CHAT_ROOM_NO)
LEFT JOIN 
    CHAT_MESSAGE cm ON (cr.CHAT_ROOM_NO = cm.CHAT_ROOM_NO)
JOIN 
    MEMBER m ON (crj.CHAT_USER_NO = m.USER_NO)
JOIN 
    IMAGE ON (IMAGE.FILE_WRITER = crj.CHAT_USER_NO)
WHERE 
    cr.CHAT_USER_NO = 5
    AND cr.STATUS = 'Y'
    AND IMAGE.FILE_LEVEL = 1
    AND cm.ENROLL_DATE = (
        SELECT MAX(cm2.ENROLL_DATE)
        FROM CHAT_MESSAGE cm2
        WHERE cm2.CHAT_ROOM_NO = cm.CHAT_ROOM_NO)
ORDER BY 
    cm.ENROLL_DATE;
   
   
   
SELECT A.CHAT_ROOM_NO, CHAT_TITLE, A.CHAT_USER_NO, USER_NICK ,
	(
		SELECT COUNT(*)
		FROM CHAT_ROOM_JOIN B
		WHERE B.CHAT_ROOM_NO = A.CHAT_ROOM_NO 
	) CNT
FROM CHAT_ROOM_JOIN A
JOIN MEMBER m ON(A.CHAT_USER_NO = USER_NO)
JOIN CHAT_ROOM C ON(A.CHAT_ROOM_NO = C.CHAT_ROOM_NO)
WHERE C.STATUS = 'Y' AND USER_NO = 5 
ORDER BY A.CHAT_ROOM_NO DESC;


SELECT *
FROM (
	SELECT *
	FROM CHAT_MESSAGE cm 
	WHERE CHAT_ROOM_NO = 11
	ORDER BY ENROLL_DATE DESC
)
WHERE ROWNUM = 1;




SELECT CHAT_ROOM_NO, FILE_PATH, CHANGE_NAME, CHAT_USER_NO
FROM CHAT_ROOM_JOIN crj 
JOIN IMAGE i ON(FILE_WRITER = CHAT_USER_NO)
WHERE CHAT_ROOM_NO = 6 AND FILE_LEVEL = 1;

SELECT CHAT_ROOM_NO
FROM CHAT_ROOM_JOIN 
WHERE CHAT_USER_NO = 5;


SELECT CHAT_ROOM_NO, FILE_PATH, CHANGE_NAME, CHAT_USER_NO
FROM CHAT_ROOM_JOIN crj 
JOIN IMAGE i ON(FILE_WRITER = CHAT_USER_NO)
WHERE CHAT_ROOM_NO IN (
		SELECT CHAT_ROOM_NO
		FROM CHAT_ROOM_JOIN 
		WHERE CHAT_USER_NO = 5
	) 
	AND FILE_LEVEL = 1
ORDER BY CHAT_ROOM_NO;


SELECT *
FROM CHAT_ROOM cr 
JOIN CHAT_ROOM_JOIN crj USING(CHAT_ROOM_NO)
JOIN MEMBER m ON(crj.CHAT_USER_NO = m.USER_NO)
WHERE CHAT_ROOM_NO = 1 AND cr.STATUS = 'Y';

SELECT CHAT_ROOM_NO, FILE_PATH, CHANGE_NAME, CHAT_USER_NO
FROM CHAT_ROOM_JOIN crj 
JOIN IMAGE i ON(FILE_WRITER = CHAT_USER_NO)
WHERE CHAT_ROOM_NO = 5
	AND FILE_LEVEL = 1;


SELECT DISTINCT FILE_PATH, CHANGE_NAME
FROM CHAT_MESSAGE cm 
JOIN IMAGE ON (FILE_WRITER = CHAT_USER_NO)
WHERE CHAT_USER_NO = 2 AND FILE_LEVEL = 1 AND CHAT_ROOM_NO = 12;
	
	
SELECT CHAT_NO, CHAT_ROOM_NO, CHAT_USER_NO, CHAT_MESSAGE , cm.ENROLL_DATE, USER_NICK ,FILE_PATH, CHANGE_NAME
FROM CHAT_MESSAGE CM
JOIN MEMBER M ON(USER_NO = CHAT_USER_NO)
JOIN IMAGE ON (USER_NO = FILE_WRITER)
WHERE CHAT_ROOM_NO = 12 AND FILE_LEVEL = 1;

	
SELECT *
FROM (
    SELECT CHAT_NO, CHAT_ROOM_NO, USER_NO, CHAT_MESSAGE, cm.ENROLL_DATE, USER_NICK, FILE_PATH, CHANGE_NAME, ORIGIN_NAME
    FROM CHAT_MESSAGE cm
    JOIN MEMBER M ON(USER_NO = CHAT_USER_NO)
    JOIN IMAGE ON (USER_NO = FILE_WRITER)
    --WHERE ORIGIN_NAME = "스크린샷 2023-08-10 오후 5.25.46.png"
    ORDER BY cm.ENROLL_DATE DESC
)
WHERE ROWNUM = 1;


SELECT CHAT_NO, CHAT_ROOM_NO, CHAT_USER_NO, CHAT_MESSAGE , cm.ENROLL_DATE, USER_NICK ,FILE_PATH, CHANGE_NAME
FROM CHAT_MESSAGE CM
JOIN MEMBER M ON(USER_NO = CHAT_USER_NO)
JOIN IMAGE ON (USER_NO = FILE_WRITER)
WHERE CHAT_ROOM_NO = 12 AND FILE_LEVEL = 1
ORDER BY cm.ENROLL_DATE;

SELECT *
FROM (
	SELECT FILE_PATH, CHANGE_NAME
	FROM IMAGE i 
	JOIN FEED ON(FEED_WRITER = FILE_WRITER)
	WHERE FEED_NO = 1 AND FILE_LEVEL = 2
	)
WHERE ROWNUM = 1;

SELECT CHAT_NO, CHAT_ROOM_NO, CHAT_USER_NO, CHAT_MESSAGE , cm.ENROLL_DATE, USER_NICK ,FILE_PATH, CHANGE_NAME, FEED_NO
FROM CHAT_MESSAGE CM
JOIN MEMBER M ON(USER_NO = CHAT_USER_NO)
JOIN IMAGE ON (USER_NO = FILE_WRITER)
WHERE CHAT_ROOM_NO = 12 AND FILE_LEVEL = 1
ORDER BY cm.ENROLL_DATE;



SELECT *
FROM MEMBER m
JOIN IMAGE ON(FILE_WRITER = USER_NO)
WHERE USER_NO = 5 AND m.STATUS = 'Y' AND FILE_LEVEL = 1;

SELECT *
FROM REPLY r
JOIN MEMBER m ON(REPLY_WRITER = USER_NO)
LEFT JOIN IMAGE i ON(USER_NO = FILE_WRITER)
WHERE REPLY_FNO = 1 AND FILE_LEVEL = 1
ORDER BY r.ENROLL_DATE DESC;

SELECT A.CHAT_ROOM_NO, CHAT_TITLE, A.CHAT_USER_NO, USER_NICK ,
	(
		SELECT COUNT(*)
		FROM CHAT_ROOM_JOIN B
		WHERE B.CHAT_ROOM_NO = A.CHAT_ROOM_NO 
	) CNT
FROM CHAT_ROOM_JOIN A
JOIN MEMBER m ON(A.CHAT_USER_NO = USER_NO)
JOIN CHAT_ROOM C ON(A.CHAT_ROOM_NO = C.CHAT_ROOM_NO)
WHERE C.STATUS = 'Y' AND USER_NO = 5 
ORDER BY A.CHAT_ROOM_NO DESC;



SELECT A.CHAT_ROOM_NO,
	(
		SELECT CHAT_TITLE
		FROM CHAT_ROOM C
		WHERE C.CHAT_ROOM_NO = A.CHAT_ROOM_NO AND STATUS = 'Y'
	) TITLE,
	A.CHAT_USER_NO, USER_NICK,
    (
        SELECT COUNT(*)
        FROM CHAT_ROOM_JOIN B
        WHERE B.CHAT_ROOM_NO = A.CHAT_ROOM_NO 
    ) CNT
FROM CHAT_ROOM_JOIN A
JOIN MEMBER m ON (A.CHAT_USER_NO = USER_NO)
WHERE USER_NO = 5
ORDER BY (
    SELECT MAX(ENROLL_DATE)
    FROM CHAT_MESSAGE CM
    WHERE CM.CHAT_ROOM_NO = A.CHAT_ROOM_NO
) DESC ;








SELECT A.CHAT_ROOM_NO,
	(
		SELECT CHAT_TITLE
		FROM CHAT_ROOM C
		WHERE C.CHAT_ROOM_NO = A.CHAT_ROOM_NO AND STATUS = 'Y'
	) CHAT_TITLE,
	A.CHAT_USER_NO, USER_NICK,
    (
        SELECT COUNT(*)
        FROM CHAT_ROOM_JOIN B
        WHERE B.CHAT_ROOM_NO = A.CHAT_ROOM_NO 
    ) CNT
FROM CHAT_ROOM_JOIN A
JOIN MEMBER m ON (A.CHAT_USER_NO = USER_NO)
WHERE USER_NO = 5 AND (
		SELECT CHAT_TITLE
		FROM CHAT_ROOM C
		WHERE C.CHAT_ROOM_NO = A.CHAT_ROOM_NO AND STATUS = 'Y'
	) LIKE '%콘크리트%'
ORDER BY (
    SELECT MAX(ENROLL_DATE)
    FROM CHAT_MESSAGE CM
    WHERE CM.CHAT_ROOM_NO = A.CHAT_ROOM_NO
) DESC;



SELECT A.CHAT_ROOM_NO, CHAT_TITLE, A.CHAT_USER_NO, USER_NICK ,
	(
		SELECT COUNT(*)
		FROM CHAT_ROOM_JOIN B
		WHERE B.CHAT_ROOM_NO = A.CHAT_ROOM_NO 
	) CNT
FROM CHAT_ROOM_JOIN A
JOIN MEMBER m ON(A.CHAT_USER_NO = USER_NO)
JOIN CHAT_ROOM C ON(A.CHAT_ROOM_NO = C.CHAT_ROOM_NO)
WHERE C.STATUS = 'Y' AND USER_NO = 2 AND CHAT_TITLE LIKE '%w%'
ORDER BY A.CHAT_ROOM_NO DESC;





SELECT *
FROM CHAT_ROOM_JOIN
WHERE CHAT_ROOM_NO = 7 AND CHAT_USER_NO != 2;


SELECT FILE_PATH, CHANGE_NAME
FROM IMAGE i 
JOIN FEED ON(FILE_FNO = FEED_NO)
WHERE FEED_NO = 998 AND FILE_LEVEL = 2

