-- 날짜는 다 DEFAULT SYSDATE 해놈

CREATE TABLE MEMBER (
	USER_NO	VARCHAR2(10) NOT NULL,
	USER_NAME VARCHAR2(30) NOT NULL,
	USER_ID	VARCHAR2(30) NOT NULL,
	USER_PWD VARCHAR2(50) NOT NULL,
	PHONE VARCHAR2(15)	NOT NULL,
	EMAIL VARCHAR2(100)	NULL,
	ADDRESS	VARCHAR2(200) NULL,
    ENROLL_DATE	DATE DEFAULT SYSDATE,
	GRADE VARCHAR2(15) NULL,
	GRADE_NO VARCHAR2(30) NOT NULL,
    STATUS VARCHAR2(1)	NOT NULL
);

CREATE TABLE BOARD (
	BOARD_NO VARCHAR2(10) NOT NULL,
    BOARD_TITLE VARCHAR2(100),
    BOARD_CATEGORY VARCHAR2(20)	NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
	COUNT NUMBER NOT NULL,
	WRITER_NO VARCHAR2(10)NOT NULL,
    STATUS VARCHAR2(1) NOT NULL
);
CREATE TABLE REPLY (
	REPLY_NO VARCHAR2(10) NOT NULL,
	REPLY_CONTENT VARCHAR2(2000) NOT NULL,
	CREATE_DATE	DATE DEFAULT SYSDATE,
	BOARD_NO VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(1)	NOT NULL
);
CREATE TABLE FAQ (
	FAQ_NO VARCHAR2(10) NOT NULL,
	FAQ_TITLE VARCHAR2(100) NOT NULL,
	FAQ_CONTENT VARCHAR2(4000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	USER_NO VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(1) NOT NULL
);

CREATE TABLE REPORT (
	REPORT_NO VARCHAR2(10)NOT NULL,
	REPORT_CONTENT VARCHAR2(4000) NOT NULL,
	CREATE_DATE	DATE DEFAULT SYSDATE,
	BOARD_NO VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(1) NOT NULL
);

CREATE TABLE DONATION (
	DONATION_NO VARCHAR2(10) NOT NULL,
	DONA_PRICE NUMBER NOT NULL,
    DONA_KIND VARCHAR2(20) NOT NULL,
	DONA_DATE DATE DEFAULT SYSDATE,
	USER_NO	VARCHAR2(10) NOT NULL
);

CREATE TABLE ATTACHMENT (
	FILE_NO VARCHAR2(10) NOT NULL,
    ORIGIN_NAME VARCHAR2(255) NOT NULL,
    CHANGE_NAME VARCHAR2(255) NOT NULL,
	FILE_PATH VARCHAR2(1000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    CATEGORY_NO VARCHAR2(10) NOT NULL,
	BOARD_NO VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(1) NOT NULL
);
-- 기존에 게시글, 분양글, 문의 번호칼럼이 각각 있던걸 BOARD_NO 하나로 통일
-- 게시글, 분양글, 문의 번호번호를 각각 B1~999, G1~999 이런식으로 써서 구분

CREATE TABLE POSTALL (
	POST_NO	VARCHAR2(10) NOT NULL,
	POST_NAME VARCHAR2(100) NOT NULL,
	POST_CONTENT VARCHAR2(4000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	RECEIVER_NO	VARCHAR2(10)NOT NULL,
	CALLER_NO VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(1) NOT NULL
);

CREATE TABLE PET (
	PET_NO VARCHAR2(10)NOT NULL,
	PET_NAME VARCHAR2(50) NOT NULL,
	PET_KIND VARCHAR2(100) NOT NULL,
	PET_AGE	NUMBER NOT NULL,
	PET_GENDER VARCHAR2(4) NOT NULL,
	PET_PRICE NUMBER NOT NULL,
	PET_RESCUE DATE	DEFAULT SYSDATE,
	STATUS VARCHAR2(1) NOT NULL
);

CREATE TABLE GETTHEPET (
	GET_NO VARCHAR2(10) NOT NULL,
	GET_CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
	PET_NO VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(1) NOT NULL
);

CREATE TABLE DELIVERY (
	DEL_NO VARCHAR2(10)	NOT NULL,
	DEL_STATUS VARCHAR2(100) NOT NULL,
	CUR_SPOT VARCHAR2(100) NULL,
	PET_NO VARCHAR2(10) NOT NULL,
	USER_NO	VARCHAR2(10) NOT NULL
);

CREATE TABLE FILECATEGORY (
	CATEGORY_NO VARCHAR2(10) NOT NULL,
	CATEGORY_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE MEMBERSHIPTIER (
	GRADE_NO VARCHAR2(10) NOT NULL,
	GRADE_NAME VARCHAR2(100) NOT NULL,
	MIN_DONA NUMBER	NOT NULL,
	MAX_DONA NUMBER	NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	USER_NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (
	REPLY_NO
);

ALTER TABLE FAQ ADD CONSTRAINT PK_FAQ PRIMARY KEY (
	FAQ_NO
);

ALTER TABLE REPORT ADD CONSTRAINT PK_REPORT PRIMARY KEY (
	REPORT_NO
);

ALTER TABLE DONATION ADD CONSTRAINT PK_DONATION PRIMARY KEY (
	DONATION_NO
);

ALTER TABLE ATTACHMENT ADD CONSTRAINT PK_ATTACHMENT PRIMARY KEY (
	FILE_NO
);

ALTER TABLE POSTALL ADD CONSTRAINT PK_POSTALL PRIMARY KEY (
	POST_NO
);

ALTER TABLE PET ADD CONSTRAINT PK_PET PRIMARY KEY (
	PET_NO
);

ALTER TABLE GETTHEPET ADD CONSTRAINT PK_GETTHEPET PRIMARY KEY (
	GET_NO
);

ALTER TABLE DELIVERY ADD CONSTRAINT PK_DELIVERY PRIMARY KEY (
	DEL_NO
);

ALTER TABLE FILECATEGORY ADD CONSTRAINT PK_FILECATEGORY PRIMARY KEY (
	CATEGORY_NO
);

ALTER TABLE MEMBERSHIPTIER ADD CONSTRAINT PK_MEMBERSHIPTIER PRIMARY KEY (
	GRADE_NO
);


COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일고유번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '원래이름';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '바뀐이름';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '저장폴더경로';
COMMENT ON COLUMN ATTACHMENT.CREATE_DATE IS '업로드일';
COMMENT ON COLUMN ATTACHMENT.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN ATTACHMENT.BOARD_NO IS '글고유번호';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '상태정보';


COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글고유번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CATEGORY IS '카테고리';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일';
COMMENT ON COLUMN BOARD.COUNT IS '조회수';
COMMENT ON COLUMN BOARD.WRITER_NO IS '회원고유번호';
COMMENT ON COLUMN BOARD.STATUS IS '상태정보';


COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글고유번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '작성일';
COMMENT ON COLUMN REPLY.BOARD_NO IS '게시글고유번호';
COMMENT ON COLUMN REPLY.STATUS IS '상태정보';


COMMENT ON COLUMN DELIVERY.DEL_NO IS '배송고유번호';
COMMENT ON COLUMN DELIVERY.DEL_STATUS IS '배송현황';
COMMENT ON COLUMN DELIVERY.CUR_SPOT IS '현재위치';
COMMENT ON COLUMN DELIVERY.PET_NO IS '동물번호';
COMMENT ON COLUMN DELIVERY.USER_NO IS '회원고유번호';


COMMENT ON COLUMN DONATION.DONATION_NO IS '후원번호';
COMMENT ON COLUMN DONATION.DONA_PRICE IS '후원금액';
COMMENT ON COLUMN DONATION.DONA_KIND IS '후원종류';
COMMENT ON COLUMN DONATION.DONA_DATE IS '후원날짜';
COMMENT ON COLUMN DONATION.USER_NO IS '회원고유번호';


COMMENT ON COLUMN FAQ.FAQ_NO IS '문의고유번호';
COMMENT ON COLUMN FAQ.FAQ_TITLE IS '문의제목';
COMMENT ON COLUMN FAQ.FAQ_CONTENT IS '문의내용';
COMMENT ON COLUMN FAQ.CREATE_DATE IS '작성일';
COMMENT ON COLUMN FAQ.USER_NO IS '회원고유번호';
COMMENT ON COLUMN FAQ.STATUS IS '상태정보';


COMMENT ON COLUMN FILECATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN FILECATEGORY.CATEGORY_NAME IS '카테고리이름';


COMMENT ON COLUMN GETTHEPET.GET_NO IS '분양글고유번호';
COMMENT ON COLUMN GETTHEPET.GET_CONTENT IS '분양글내용';
COMMENT ON COLUMN GETTHEPET.CREATE_DATE IS '작성일';
COMMENT ON COLUMN GETTHEPET.PET_NO IS '동물번호';
COMMENT ON COLUMN GETTHEPET.STATUS IS '상태정보';


COMMENT ON COLUMN MEMBER.USER_NO IS '회원고유번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원명';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.GRADE IS '후원등급';
COMMENT ON COLUMN MEMBER.GRADE_NO IS '후원등급번호';
COMMENT ON COLUMN MEMBER.STATUS IS '상태정보';


COMMENT ON COLUMN MEMBERSHIPTIER.GRADE_NO IS '후원등급번호';
COMMENT ON COLUMN MEMBERSHIPTIER.GRADE_NAME IS '후원등급이름';
COMMENT ON COLUMN MEMBERSHIPTIER.MIN_DONA IS '최소누적금액';
COMMENT ON COLUMN MEMBERSHIPTIER.MAX_DONA IS '최대누적금액';


COMMENT ON COLUMN PET.PET_NO IS '동물번호';
COMMENT ON COLUMN PET.PET_NAME IS '동물이름';
COMMENT ON COLUMN PET.PET_KIND IS '동물종류';
COMMENT ON COLUMN PET.PET_AGE IS '동물나이';
COMMENT ON COLUMN PET.PET_GENDER IS '동물성별';
COMMENT ON COLUMN PET.PET_PRICE IS '분양가';
COMMENT ON COLUMN PET.PET_RESCUE IS '구조일';
COMMENT ON COLUMN PET.STATUS IS '상태정보';


COMMENT ON COLUMN POSTALL.POST_NO IS '쪽지고유번호';
COMMENT ON COLUMN POSTALL.POST_NAME IS '쪽지제목';
COMMENT ON COLUMN POSTALL.POST_CONTENT IS '쪽지내용';
COMMENT ON COLUMN POSTALL.CREATE_DATE IS '작성일';
COMMENT ON COLUMN POSTALL.RECEIVER_NO IS '수신자회원번호';
COMMENT ON COLUMN POSTALL.CALLER_NO IS '발신자회원번호';
COMMENT ON COLUMN POSTALL.STATUS IS '상태정보';


COMMENT ON COLUMN REPORT.REPORT_NO IS '신고글고유번호';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고내용';
COMMENT ON COLUMN REPORT.CREATE_DATE IS '작성일';
COMMENT ON COLUMN REPORT.BOARD_NO IS '게시글고유번호';
COMMENT ON COLUMN REPORT.STATUS IS '상태정보';

COMMIT;